language: cpp
os: linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - build-essential
      - cmake
      - libboost-dev
      - libmpich-dev
      - autoconf
      - autoconf-archive
      - automake
      - gfortran
      - g++-7
      - libstdc++-7-dev

before_install:   
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - git clone https://xgitlab.cels.anl.gov/sds/sds-repo.git
  - (cd $HOME/spack; git describe) || git clone https://github.com/spack/spack $HOME/spack
  - |
    test -f $HOME/spack/etc/spack/packages.yaml || cat > $HOME/spack/etc/spack/packages.yaml << '  EOF'
    packages:
      all:
        target: [x86_64]
      boost:
        paths:
          boost@1.72.0: /usr
        buildable: False
      mpich:
        paths:
          mpich@3.3: /opt/mpich-3.3-intel
        buildable: False
      cmake:
        paths:
          cmake@3.10.0: /usr/local/cmake-3.10.0
        buildable: False
      autoconf:
        paths:
          autoconf@2.69: /usr
        buildable: False
      automake:
        paths:
          automake@1.15: /usr
        buildable: False
      libtool:
        paths:
          libtool@2.4.6: /usr
        buildable: False
      m4:
        paths:
          m4@4.17: /usr
        buildable: False
    EOF
install:
  - . $HOME/spack/share/spack/setup-env.sh
  - spack install gotcha@develop && spack load gotcha@develop
  - spack install glog@0.3.5 && spack load glog@0.3.5
  - spack repo add sds-repo
  - spack install mochi-thallium~cereal && spack load -r mochi-thallium~cereal

script: ./ci/install_hermes.sh

