/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hermes_java_Blob */

#ifndef _Included_hermes_java_Blob
#define _Included_hermes_java_Blob
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hermes_java_Blob
 * Method:    fromString
 * Signature: (Ljava/lang/String;)Lhermes/java/Blob;
 */
JNIEXPORT jobject JNICALL Java_hermes_java_Blob_fromString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     hermes_java_Blob
 * Method:    freeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hermes_java_Blob_freeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
