/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "hermes_java_wrapper.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     hermes_java_Blob
 * Method:    freeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hermes_java_Blob_freeNative(JNIEnv *env,
                                                         jobject blob_java) {
  hapi::Blob blob = HERMES_JAVA_WRAPPER->GetBlobFromJava(env, blob_java);
  blob.destructable_ = true;
}

#ifdef __cplusplus
}
#endif
