version: "3"

services:
  node1:
    build: .
    links: 
      - node2
    networks:
      - net
    volumes:
      - $HOME:$HOME
    hostname: node1

  node2:
    build: .
    networks:
      - net
    volumes:
      - $HOME:$HOME
    hostname: node2

networks:
  net:
    driver: bridge
