from __future__ import print_function
import sys

class func:

	def __init__(self, prototype):
		l = prototype.strip().split('(')
		x = filter(None, l[0].split(' '))
		self.ret_type = ' '.join(x[0:-1])
		self.name = x[-1]
		self.arg_string = l[1].strip(")")
		# set up useful vars
		self.name_quote = "\"" + self.name + "\""
		self.wraper = "dissectio_" + self.name
		self.wrapee = "WRAP_" + self.name
		self.string_param_names = ""
		# param list of tuples: (type, name)
		self.list_params = []
		params = filter(None, self.arg_string.split(','))
		for y in params:
			param_name = y.split(' ')[-1].strip().strip('*')
			param_type = y[0:-1*len(param_name)].strip()
			self.string_param_names += param_name + ", "
			self.list_params.append((param_type, param_name))
		self.string_param_names = self.string_param_names[:-2]

	def __str__(self):
		return self.ret_type + ' ' + self.name + ' (' + self.arg_string + ')'

def read_functions_file(filename):
	functions = []
	f = open(filename, 'r')
	for line in f:
		functions.append(func(line))
	f.close()
	return functions


def write_gotcha_file(filename, func_list, modulename):
        """static gotcha_wrappee_handle_t WRAP_Orig_Func_handle;
static int (*WRAP_Orig_Func) (int param);
static int dissectio_Orig_Func (int param){
	printf("Orig_Func\n");
        WRAP_Orig_Func = gotcha_get_wrappee(WRAP_Orig_Func_handle);
        return WARP_Orig_Func ? (WRAP_Orig_Func(param) ) : 0;
}
"""
	m = modulename.split('_')[0]
	f = open(filename, 'w')
	# write header
	f.write("//Generated by hermes_intercept.py\n\n")
	f.write("#include <gotcha/gotcha.h>\n")
	f.write("#include <" + m + ".h>\n")
	f.write("#include <stdio.h>\n")
	f.write("\n#define NFUNCS " + str(len(func_list)) + "\n\n")
	# write each function wraper and wrapee
	for function in func_list:
                f.write("static gotcha_wrappee_handle_t " + function.wrapee + "_handle;\n")
		f.write("static " + function.ret_type + " (*" + function.wrapee + ") (" + function.arg_string + ");\n")
		f.write("static " + function.ret_type + " " + function.wraper + " (" + function.arg_string + "){\n")
                f.write("\t" + function.wrapee + " = gotcha_get_wrappee(" + function.wrapee  + "_handle);\n" )
		f.write("\treturn " + function.wrapee + " ? (" + function.wrapee + "(" + function.string_param_names + ")) : 0;\n")
		f.write("}\n\n")
	f.write("\n")
	# write map struct
	f.write("struct gotcha_binding_t wrap_" + modulename + " [] = {\n")
	for function in func_list:
		f.write("\t{ " + function.name_quote + ", " + function.wraper + ", &" + function.wrapee + " },\n")
	f.write("};\n\n")
	# write initializer
	f.write("void init_gotcha_" + modulename + " () {\n")
	f.write("\tgotcha_wrap(wrap_"+ modulename +", NFUNCS, \"dissectio\");\n")
	f.write("}\n")
	f.close()

def main(modulename):
	functions = read_functions_file(modulename+".txt")
	write_gotcha_file("gotcha_"+modulename+".c", functions, modulename)


if __name__ == "__main__":
	if len(sys.argv) < 2:
		print("Usage: python", sys.argv[0], "modulename")
	else:
		main(sys.argv[1])
