#!/usr/bin/env python3

"""
USAGE:
    cd code_generators/bin
    python3 hermes_config.py

OUTPUT:
    ${HERMES}/src/config_client_default.h (if client)
    ${HERMES}/src/config_server_default.h (if server)
"""

from codegen.hrun_config.generator import create_config
from codegen.util.paths import HRUN_ROOT

HERMES_ROOT = f'{HRUN_ROOT}/tasks/hermes'
create_config(
    path=f"{HERMES_ROOT}/config/hermes_client_default.yaml",
    var_name="kHermesClientDefaultConfigStr",
    config_path=f"{HERMES_ROOT}/include/hermes/config_client_default.h",
    macro_name="CLIENT"
)

create_config(
    path=f"{HERMES_ROOT}/config/hermes_server_default.yaml",
    var_name="kHermesServerDefaultConfigStr",
    config_path=f"{HERMES_ROOT}/include/hermes/config_server_default.h",
    macro_name="SERVER"
)
