#!/usr/bin/env python3

"""
USAGE: ./make_macro [PATH]
"""

import os
import sys
from codegen.hrun_config.generator import print_macro

PATH = sys.argv[1]
MACRO_NAME = os.path.basename(PATH).upper().split('.')[0]
print_macro(PATH, MACRO_NAME)
