/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "src_main_Bucket.h"
#include "hermes_java_wrapper.h"
#include <hermes.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     src_main_Bucket
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_destroy(JNIEnv *env,
                                                         jobject bkt_java) {
  hapi::Bucket bkt = HERMES_JAVA_WRAPPER->GetBucketFromJava(env, bkt_java);
  bkt.Destroy();
}

/*
 * Class:     src_main_Bucket
 * Method:    Get
 * Signature: (Lsrc/main/UniqueId;)Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_src_main_java_Bucket_get(JNIEnv *env,
                                                        jobject bkt_java,
                                                        jobject blob_id_java) {
  std::cout << __func__ << std::endl;
  hapi::Bucket bkt = HERMES_JAVA_WRAPPER->GetBucketFromJava(env, bkt_java);
  auto blob_id = HERMES_JAVA_WRAPPER->GetUniqueIdFromJava<hermes::BlobId>(
      env, blob_id_java);
  hapi::Blob blob;
  hapi::Context ctx;
  bkt.Get(blob_id, blob, ctx);
  jobject blob_java = HERMES_JAVA_WRAPPER->ConvertBlobToJava(env, blob);
  return blob_java;
}

/*
 * Class:     src_main_Bucket
 * Method:    Put
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lsrc/main/UniqueId;
 */
JNIEXPORT jobject JNICALL Java_src_main_java_Bucket_put(JNIEnv *env,
                                                        jobject bkt_java,
                                                        jstring blob_name_java,
                                                        jobject blob_java) {
  hapi::Context ctx;
  hermes::BlobId blob_id;
  hapi::Blob blob = HERMES_JAVA_WRAPPER->GetBlobFromJava(env, blob_java);
  hapi::Bucket bkt = HERMES_JAVA_WRAPPER->GetBucketFromJava(env, bkt_java);
  JavaStringWrap blob_name(env, blob_name_java);
  bkt.Put(blob_name.data_, blob, blob_id, ctx);
  return HERMES_JAVA_WRAPPER->ConvertUniqueIdToJava(env, blob_id);
}

/*
 * Class:     src_main_Bucket
 * Method:    DestroyBlob
 * Signature: (Lsrc/main/UniqueId;)V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_destroyBlob(
    JNIEnv *env, jobject bkt_java, jobject blob_id_java) {
  hapi::Context ctx;
  auto blob_id = HERMES_JAVA_WRAPPER->GetUniqueIdFromJava<hermes::BlobId>(
      env, blob_id_java);
  hapi::Bucket bkt = HERMES_JAVA_WRAPPER->GetBucketFromJava(env, bkt_java);
  bkt.DestroyBlob(blob_id, ctx);
}

#ifdef __cplusplus
}
#endif
