/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_main_Hermes */

#ifndef _Included_src_main_Hermes
#define _Included_src_main_Hermes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_main_Hermes
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_main_java_Hermes_create
  (JNIEnv *, jobject);

/*
 * Class:     src_main_Hermes
 * Method:    getBucket
 * Signature: (Ljava/lang/String;)Lsrc/main/Bucket;
 */
JNIEXPORT jobject JNICALL Java_src_main_java_Hermes_getBucket
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
