/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "src_main_Bucket.h"
#include "hermes_java_wrapper.h"
#include <hermes.h>

#ifdef __cplusplus
extern "C" {
#endif

/**====================================
 * BUCKET operations
 * ===================================*/

/*
 * Class:     src_main_java_Bucket
 * Method:    lock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_lock(JNIEnv *env,
                                                      jobject bkt_java,
                                                      jint lock_type_java) {
  auto bkt = HERMES_JAVA_WRAPPER->
      GetBucketFromJava(env, bkt_java);
  auto lock_type = static_cast<hermes::MdLockType>(lock_type_java);
  bkt.LockBucket(lock_type);
}

/*
 * Class:     src_main_java_Bucket
 * Method:    unlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_unlock(JNIEnv *env,
                                                        jobject bkt_java,
                                                        jint lock_type_java) {
  auto bkt = HERMES_JAVA_WRAPPER->
      GetBucketFromJava(env, bkt_java);
  auto lock_type = static_cast<hermes::MdLockType>(lock_type_java);
  bkt.UnlockBucket(lock_type);
}

/*
 * Class:     src_main_java_Bucket
 * Method:    getContainedBlobIds
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_src_main_java_Bucket_getContainedBlobIds(
    JNIEnv *env, jobject bkt_java) {
  auto bkt = HERMES_JAVA_WRAPPER->
      GetBucketFromJava(env, bkt_java);
  std::vector<hermes::BlobId> blob_ids = bkt.GetContainedBlobIds();
  return HERMES_JAVA_WRAPPER->ConvertBlobIdVectorToJava(env, blob_ids);
}

/*
 * Class:     src_main_Bucket
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_destroy(JNIEnv *env,
                                                         jobject bkt_java) {
  hapi::Bucket bkt = HERMES_JAVA_WRAPPER->GetBucketFromJava(env, bkt_java);
  bkt.Destroy();
}

/**====================================
 * BLOB operations
 * ===================================*/

/*
 * Class:     src_main_Bucket
 * Method:    get
 * Signature: (Lsrc/main/UniqueId;)Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_src_main_java_Bucket_get(JNIEnv *env,
                                                        jobject bkt_java,
                                                        jobject blob_id_java) {
  hapi::Bucket bkt = HERMES_JAVA_WRAPPER->GetBucketFromJava(env, bkt_java);
  auto blob_id = HERMES_JAVA_WRAPPER->GetUniqueIdFromJava<hermes::BlobId>(
      env, blob_id_java);
  hapi::Blob blob;
  hapi::Context ctx;
  bkt.Get(blob_id, blob, ctx);
  jobject blob_java = HERMES_JAVA_WRAPPER->ConvertBlobToJava(env, blob);
  return blob_java;
}

/*
 * Class:     src_main_Bucket
 * Method:    put
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lsrc/main/UniqueId;
 */
JNIEXPORT jobject JNICALL Java_src_main_java_Bucket_put(JNIEnv *env,
                                                        jobject bkt_java,
                                                        jstring blob_name_java,
                                                        jobject blob_java) {
  hapi::Context ctx;
  hermes::BlobId blob_id;
  hapi::Blob blob = HERMES_JAVA_WRAPPER->GetBlobFromJava(env, blob_java);
  hapi::Bucket bkt = HERMES_JAVA_WRAPPER->GetBucketFromJava(env, bkt_java);
  JavaStringWrap blob_name(env, blob_name_java);
  bkt.Put(blob_name.data_, blob, blob_id, ctx);
  return HERMES_JAVA_WRAPPER->ConvertUniqueIdToJava(env, blob_id);
}

/*
 * Class:     src_main_java_Bucket
 * Method:    lockBlob
 * Signature: (Lsrc/main/java/UniqueId;)V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_lockBlob
  (JNIEnv *env, jobject bkt_java, jobject blob_id_java, jint lock_type_java) {
  auto blob_id = HERMES_JAVA_WRAPPER->
      GetUniqueIdFromJava<hermes::BlobId>(env, blob_id_java);
  auto bkt = HERMES_JAVA_WRAPPER->
      GetBucketFromJava(env, bkt_java);
  auto lock_type = static_cast<hermes::MdLockType>(lock_type_java);
  bkt.LockBlob(blob_id, lock_type);
}

/*
 * Class:     src_main_java_Bucket
 * Method:    unlockBlob
 * Signature: (Lsrc/main/java/UniqueId;)V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_unlockBlob
  (JNIEnv *env, jobject bkt_java, jobject blob_id_java, jint lock_type_java) {
  auto blob_id = HERMES_JAVA_WRAPPER->
      GetUniqueIdFromJava<hermes::BlobId>(env, blob_id_java);
  auto bkt = HERMES_JAVA_WRAPPER->
      GetBucketFromJava(env, bkt_java);
  auto lock_type = static_cast<hermes::MdLockType>(lock_type_java);
  bkt.UnlockBlob(blob_id, lock_type);
}

/*
 * Class:     src_main_Bucket
 * Method:    DestroyBlob
 * Signature: (Lsrc/main/UniqueId;)V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_destroyBlob(
    JNIEnv *env, jobject bkt_java, jobject blob_id_java) {
  hapi::Context ctx;
  auto blob_id = HERMES_JAVA_WRAPPER->GetUniqueIdFromJava<hermes::BlobId>(
      env, blob_id_java);
  hapi::Bucket bkt = HERMES_JAVA_WRAPPER->GetBucketFromJava(env, bkt_java);
  bkt.DestroyBlob(blob_id, ctx);
}

#ifdef __cplusplus
}
#endif
