/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_main_Bucket
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_main_Bucket_Destroy(JNIEnv *env, jobject obj) {
}

/*
 * Class:     src_main_Bucket
 * Method:    Get
 * Signature: (Lsrc/main/UniqueId;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_main_Bucket_Get(JNIEnv *env, jobject obj, jobject bkt_id) {
}

/*
 * Class:     src_main_Bucket
 * Method:    Put
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lsrc/main/UniqueId;
 */
JNIEXPORT jobject JNICALL Java_src_main_Bucket_Put(JNIEnv *env, jobject obj, jstring blob_name, jstring data) {
}

/*
 * Class:     src_main_Bucket
 * Method:    DestroyBlob
 * Signature: (Lsrc/main/UniqueId;)V
 */
JNIEXPORT void JNICALL Java_src_main_Bucket_DestroyBlob(JNIEnv *env, jobject obj, jobject blob_id) {
}

#ifdef __cplusplus
}
#endif
