/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_main_java_Bucket */

#ifndef _Included_src_main_java_Bucket
#define _Included_src_main_java_Bucket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_main_java_Bucket
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_destroy
    (JNIEnv *, jobject);

/*
 * Class:     src_main_java_Bucket
 * Method:    get
 * Signature: (Lsrc/main/java/UniqueId;)Lsrc/main/java/Blob;
 */
JNIEXPORT jobject JNICALL Java_src_main_java_Bucket_get
    (JNIEnv *, jobject, jobject);

/*
 * Class:     src_main_java_Bucket
 * Method:    put
 * Signature: (Ljava/lang/String;Lsrc/main/java/Blob;)Lsrc/main/java/UniqueId;
 */
JNIEXPORT jobject JNICALL Java_src_main_java_Bucket_put
    (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     src_main_java_Bucket
 * Method:    destroyBlob
 * Signature: (Lsrc/main/java/UniqueId;)V
 */
JNIEXPORT void JNICALL Java_src_main_java_Bucket_destroyBlob
    (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
