/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_main_java_Blob */

#ifndef _Included_src_main_java_Blob
#define _Included_src_main_java_Blob
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_main_java_Blob
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_main_java_Blob_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
