packages:
  perl:
    externals:
      - spec: perl@5.34.0~cpanm+open+shared+threads
        prefix: /usr
  cmake:
    externals:
      - spec: cmake@3.22.1
        prefix: /usr
  m4:
    externals:
      - spec: m4@1.4.18
        prefix: /usr
  binutils:
    externals:
      - spec: binutils@2.38
        prefix: /usr
  pkg-config:
    externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
  findutils:
    externals:
      - spec: findutils@4.8.0
        prefix: /usr
  coreutils:
    externals:
      - spec: coreutils@8.32
        prefix: /usr
  gmake:
    externals:
      - spec: gmake@4.3
        prefix: /usr
  openssl:
    externals:
      - spec: openssl@3.0.2
        prefix: /usr
  git:
    externals:
      - spec: git@2.34.1~tcltk
        prefix: /usr
  doxygen:
    externals:
      - spec: doxygen@1.9.1~graphviz~mscgen
        prefix: /usr
  openssh:
    externals:
      - spec: openssh@8.9p1
        prefix: /usr
  tar:
    externals:
      - spec: tar@1.34
        prefix: /usr
  diffutils:
    externals:
      - spec: diffutils@3.8
        prefix: /usr
  bzip2:
    externals:
      - spec: bzip2@1.0.8
        prefix: /usr
