/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Distributed under BSD 3-Clause license.                                   *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Illinois Institute of Technology.                        *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of Hermes. The full Hermes copyright notice, including  *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the top directory. If you do not  *
 * have access to the file, you may request a copy from help@hdfgroup.org.   *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#ifndef HERMES_ADAPTER_STDIO_NATIVE_H_
#define HERMES_ADAPTER_STDIO_NATIVE_H_

#include <memory>

#include "adapter/filesystem/filesystem.h"
#include "adapter/filesystem/filesystem_mdm.h"
#include "stdio_api_singleton_macros.h"
#include "stdio_api.h"
#include "stdio_io_client.h"

namespace hermes::adpater::fs {

/** A class to represent POSIX IO file system */
class StdioFs : public hermes::adapter::fs::Filesystem {
 public:
  StdioFs() : hermes::adapter::fs::Filesystem(HERMES_STDIO_IO_CLIENT,
                                              AdapterType::kStdio) {}
  
  /** Whether or not \a fd FILE DESCRIPTOR was generated by Hermes */
  static bool IsFpTracked(FILE* fp) {
    if (!HERMES->IsInitialized()) {
      return false;
    }
    hermes::adapter::fs::File f;
    f.hermes_fh_ = fp;
    std::pair<AdapterStat*, bool> stat_pair =
        HERMES_FS_METADATA_MANAGER->Find(f);
    return stat_pair.second;
  }

  /** get the file name from \a fp file pointer */
  inline std::string GetFilenameFromFP(FILE* fp) {
    char proclnk[kMaxPathLen];
    char filename[kMaxPathLen];
    int fno = fileno(fp);
    snprintf(proclnk, kMaxPathLen, "/proc/self/fd/%d", fno);
    size_t r = readlink(proclnk, filename, kMaxPathLen);
    filename[r] = '\0';
    return filename;
  }
};

/** Simplify access to the stateless StdioFs Singleton */
#define HERMES_STDIO_FS \
  hermes::EasyGlobalSingleton<hermes::adapter::fs::StdioFs>::GetInstance()
#define HERMES_STDIO_FS_T hermes::adapter::fs::StdioFs*

}  // namespace hermes::adapter::fs

#endif  // HERMES_ADAPTER_STDIO_NATIVE_H_
