/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Distributed under BSD 3-Clause license.                                   *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Illinois Institute of Technology.                        *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of Hermes. The full Hermes copyright notice, including  *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the top directory. If you do not  *
 * have access to the file, you may request a copy from help@hdfgroup.org.   *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#ifndef HERMES_ADAPTER_POSIX_NATIVE_H_
#define HERMES_ADAPTER_POSIX_NATIVE_H_

#include <memory>

#include "adapter/filesystem/filesystem.h"
#include "adapter/filesystem/filesystem_mdm.h"
#include "io_client/posix/posix_api.h"
#include "io_client/posix/posix_io_client.h"

namespace hermes::adapter::fs {

/** A class to represent POSIX IO file system */
class PosixFs : public hermes::adapter::fs::Filesystem {
 public:
  PosixFs() : hermes::adapter::fs::Filesystem(HERMES_POSIX_IO_CLIENT,
                                              AdapterType::kPosix) {}

  template<typename StatT>
  int Stat(File &f, StatT *buf) {
    auto mdm = HERMES_FS_METADATA_MANAGER;
    auto existing = mdm->Find(f);
    if (existing) {
      AdapterStat &astat = *existing;
      // TODO(chogan): st_dev and st_ino need to be assigned by us, but
      // currently we get them by calling the real fstat on open.
      buf->st_dev = 0;
      buf->st_ino = 0;
      buf->st_mode = astat.st_mode_;
      buf->st_nlink = 0;
      buf->st_uid = astat.st_uid_;
      buf->st_gid = astat.st_gid_;
      buf->st_rdev = 0;
      buf->st_size = GetSize(f, astat);
      // buf->st_blksize = astat.st_blksize_;
      buf->st_blocks = 0;
      buf->st_atime = astat.st_atim_.tv_sec;
      buf->st_mtime = astat.st_mtim_.tv_sec;
      buf->st_ctime = astat.st_ctim_.tv_sec;
      return 0;
    } else {
      errno = EBADF;
      HELOG(kError, "File with descriptor {} does not exist in Hermes",
            f.hermes_fd_)
      return -1;
    }
  }

  template<typename StatT>
  int Stat(const char *__filename, StatT *buf) {
    bool stat_exists;
    AdapterStat stat;
    stat.flags_ = O_RDONLY;
    stat.st_mode_ = 0;
    stat.adapter_mode_ = AdapterMode::kScratch;
    File f = Open(stat, __filename);
    int result = Stat(f, buf);
    Close(f, stat_exists);
    return result;
  }

  /** Whether or not \a fd FILE DESCRIPTOR was generated by Hermes */
  static bool IsFdTracked(int fd, std::shared_ptr<AdapterStat> &stat) {
    if (!HERMES->IsInitialized() || fd < 8192) {
      return false;
    }
    hermes::adapter::fs::File f;
    f.hermes_fd_ = fd;
    stat = HERMES_FS_METADATA_MANAGER->Find(f);
    return stat != nullptr;
  }

  /** Whether or not \a fd FILE DESCRIPTOR was generated by Hermes */
  static bool IsFdTracked(int fd) {
    std::shared_ptr<AdapterStat> stat;
    return IsFdTracked(fd, stat);
  }

  /** get the file name from \a fd file descriptor */
  std::string GetFilenameFromFD(int fd) {
    char proclnk[kMaxPathLen];
    char filename[kMaxPathLen];
    snprintf(proclnk, kMaxPathLen, "/proc/self/fd/%d", fd);
    size_t r = readlink(proclnk, filename, kMaxPathLen);
    filename[r] = '\0';
    return filename;
  }
};

/** Simplify access to the stateless PosixFs Singleton */
#define HERMES_POSIX_FS \
  hshm::EasySingleton<hermes::adapter::fs::PosixFs>::GetInstance()
#define HERMES_POSIX_FS_T hermes::adapter::fs::PosixFs*

}  // namespace hermes::adapter::fs

#endif  // HERMES_ADAPTER_POSIX_NATIVE_H_
