/* hermes_config.h Generated by cmake with CMakelists.txt from hermes_config.h.cmake */

#cmakedefine GLOG_TO_CONSOLE 

#cmakedefine HERMES_GLOG_SEVERITY_LEVEL @HERMES_GLOG_SEVERITY_LEVEL@ 

#cmakedefine HERMES_GLOG_VERBOSE_LEVEL @HERMES_GLOG_VERBOSE_LEVEL@
